// Mocks generated by Mockito 5.4.6 from annotations
// in app_filmes/test/widget/add_genero_form_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app_filmes/models/genero.dart' as _i2;
import 'package:app_filmes/repositories/genero_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGenero_0 extends _i1.SmartFake implements _i2.Genero {
  _FakeGenero_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GeneroRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeneroRepository extends _i1.Mock implements _i3.GeneroRepository {
  MockGeneroRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Genero> salvarGenero(_i2.Genero? genero) =>
      (super.noSuchMethod(
            Invocation.method(#salvarGenero, [genero]),
            returnValue: _i4.Future<_i2.Genero>.value(
              _FakeGenero_0(this, Invocation.method(#salvarGenero, [genero])),
            ),
          )
          as _i4.Future<_i2.Genero>);

  @override
  _i4.Future<List<_i2.Genero>> listarGeneros() =>
      (super.noSuchMethod(
            Invocation.method(#listarGeneros, []),
            returnValue: _i4.Future<List<_i2.Genero>>.value(<_i2.Genero>[]),
          )
          as _i4.Future<List<_i2.Genero>>);

  @override
  _i4.Future<int> excluirGenero(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#excluirGenero, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> atualizarGenero(_i2.Genero? genero) =>
      (super.noSuchMethod(
            Invocation.method(#atualizarGenero, [genero]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}
